### ISSUE TITLE
Migrate to v4

### ISSUE THREAD

**Issue by brookerose1312** [bztes/strapi-provider-email-gmail-api#2]
Hi, Strapi v4 released a few days ago, and I'm wondering if/when migration to v4 will happen?

Thanks

**Comment by bztes** [comment]
As far as I can see, the interface has not changed, so the provider should still work. I'll try it out at the weekend.

**Comment by saintego** [comment]
Hi,
readme for v3 is wrong. It's necessary to have strapi-provider-email-gmail-api at package.json and plugins.js is without config part.
